spring.application.name=demo
spring.cloud.function.definition=UserLambdaHandler

# PonaCash API Configuration
# ponacash.api.url=http://host.docker.internal:8003/api/kofuta/financial-transaction/
# ponacash.auth.url=http://host.docker.internal:8003/api/kofuta/token/
ponacash.api.url=https://test1.fouta.finances.gouv.cg/api/kofuta/financial-transaction/
ponacash.auth.url=https://test1.fouta.finances.gouv.cg/api/kofuta/token/
ponacash.auth.solution-reference=gAAAAABpd-bV5rafzlv-EB72lu0HsRPvC0kL-yOIICLtwE5hcj8CXb2iqdWX_PBEgsh7sfsdIUg_mcasDLXD7mjXOnl25z8a_g==
ponacash.auth.client-username=242060000001
# ponacash.auth.client-username=242061245540
ponacash.solution.id=YOUR_SOLUTION_ID
ponacash.redirect.url=https://mon.site.com
